import frappe

data = [
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"after_insert\",\n    \"doctype\": \"Payment Request\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "V7lvg8fLqqnTjtnqkrP2F",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": -150\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment links For 1st Installment For All Students\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "3sScfFhiE-qfOMbSpZgR0",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1215,\n    \"y\": 135\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Student\",\n    \"python_code\": \"# do required updates\\n# update variable e.g.\\ndoc = variables.get(\\\"doc\\\")\\n\\nfee = frappe.get_doc(doc.reference_doctype, doc.reference_name)\\n\\nacad_year = fee.academic_year\\n\\nyear = \\\"2024\\\"\\n\\nprogram = fee.program if doc.doctype == \\\"Fees\\\" else fee.next_program\\nclass_group = frappe.db.get_value(\\\"Program\\\", program, \\\"class_group\\\")\\n\\nstudent = frappe.get_doc(\\\"Student\\\", doc.party)\\n\\npayment_plan = frappe.db.get_value(doc.reference_doctype, doc.reference_name, \\\"payment_plan\\\")\\n\\npayplan_doc = frappe.get_doc(\\\"Payment Plan\\\", payment_plan)\\ninst_count = len(payplan_doc.payment_schedule)\\n\\nvariables[\\\"class_group\\\"] = class_group\\n\\nvariables[\\\"first_name\\\"] = student.first_name\\nvariables[\\\"middle_name\\\"] = student.middle_name\\nvariables[\\\"last_name\\\"] = student.last_name\\nvariables[\\\"status\\\"] = student.student_status\\nvariables[\\\"class_name\\\"] = fee.program\\nvariables[\\\"acad_year\\\"] = acad_year\\nvariables[\\\"year\\\"] = year\\nvariables[\\\"link\\\"] = doc.payment_url\\nvariables[\\\"refno\\\"] = student.reference_number\\nvariables[\\\"inst_count\\\"] = inst_count\\nvariables[\\\"recipient\\\"] =student.student_email_id\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "60MS7MC_fA4ZM-B_oL48R",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": -75\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-V7lvg8fLqqnTjtnqkrP2Foutput-60MS7MC_fA4ZM-B_oL48Rinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "V7lvg8fLqqnTjtnqkrP2F",
    "sourcehandle": "output",
    "target": "60MS7MC_fA4ZM-B_oL48R",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"expression\": \"doc = variables.get('doc')\\nif doc.payment_term:\\n    return True\\nelse:\\n    return False\",\n    \"node_label\": \"Filter Deposit and Normal Payment Link\",\n    \"submit\": true,\n    \"use_python_expression\": true\n}",
    "element_type": "Action",
    "id": "VhNcdxGhb5FNz6PkaF9SN",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 0\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Deposit Link (Original Content)\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "V1FggHybsRoyMO2N4PJ0C",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1215,\n    \"y\": 45\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for New Students Std. 1 to 10\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "nN6Btz--ZAOQR4mwDRyAH",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 2130,\n    \"y\": 480\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for New Students Std. 1 to 10\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "aVYGk4nvN42GHJkSCWTKC",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1020,\n    \"y\": 420\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for New Students Std. 1 to 10\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "bx8ahgUuB7rOcLze37LbJ",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1185,\n    \"y\": 360\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for New Students Std. 1 to 10\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "UNGeLpOF9CSt7pCaTo6uQ",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 2310,\n    \"y\": 435\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"expression\": \"status = variables.get(\\\"status\\\")\\nif status == \\\"Current Student\\\":\\n    return True\\nelif status == \\\"New Student\\\":\\n    return False\",\n    \"filters\": [],\n    \"node_label\": \"Filter Student Status\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "ktDwwAvcV2qqSoA6H49ur",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-60MS7MC_fA4ZM-B_oL48Routput-VhNcdxGhb5FNz6PkaF9SNinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "60MS7MC_fA4ZM-B_oL48R",
    "sourcehandle": "output",
    "target": "VhNcdxGhb5FNz6PkaF9SN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"expression\": \"class_group = variables.get(\\\"class_group\\\")\\nif class_group == \\\"KG\\\":\\n    return True\\nelif class_group == \\\"Senior KG\\\":\\n    return False\",\n    \"filters\": [],\n    \"node_label\": \"Filter KG\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "fbe2yiJaAgQa033lXATO1",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1575,\n    \"y\": 330\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"expression\": \"class_group = variables.get(\\\"class_group\\\")\\nif class_group == \\\"KG\\\":\\n    return True\\nelif class_group == \\\"Senior KG\\\":\\n    return False\",\n    \"filters\": [],\n    \"node_label\": \"Filter KG\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "jm_Rhj2CVI_Yv4OZslAUW",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 600,\n    \"y\": 315\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"expression\": \"doc = variables.get(\\\"doc\\\")\\nif doc.payment_term == \\\"Term 1\\\":\\n    return False\\nelse:\\n    return True\",\n    \"filters\": [],\n    \"node_label\": \"Filter Installment\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "eBl97XtjA8KwduM0J8zo6",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 90\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"expression\": \"class_group = variables.get(\\\"class_group\\\")\\nif class_group == \\\"Primary\\\":\\n    return True\\nelif class_group == \\\"Secondary\\\":\\n    return False\",\n    \"filters\": [],\n    \"node_label\": \"Filter Primary/Secondary\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "1m2YWLNGNSVz9aaYIfJIu",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 2130,\n    \"y\": 375\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"expression\": \"class_group = variables.get(\\\"class_group\\\")\\nif class_group == \\\"Primary\\\":\\n    return True\\nelif class_group == \\\"Secondary\\\":\\n    return False\",\n    \"filters\": [],\n    \"node_label\": \"Filter Primary/Secondary\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "S2WR9WbUO2lKaGshG8_Pp",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1020,\n    \"y\": 315\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for Senior KG current students\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "g7y_U3muCH_YWRTjPIl_S",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1740,\n    \"y\": 375\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for Senior KG current students\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "DMCso1OEIqjB1lPLKUzHS",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 765,\n    \"y\": 360\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment Link NR & JR KG\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "BTdeYK_AhNBR5DV8W0XPP",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1575,\n    \"y\": 435\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment Link NR & JR KG\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "OFAAVVDKwYSCUTQQhs_Xj",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 600,\n    \"y\": 405\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-VhNcdxGhb5FNz6PkaF9SNno-V1FggHybsRoyMO2N4PJ0Cinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "VhNcdxGhb5FNz6PkaF9SN",
    "sourcehandle": "no",
    "target": "V1FggHybsRoyMO2N4PJ0C",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ktDwwAvcV2qqSoA6H49uryes-jm_Rhj2CVI_Yv4OZslAUWinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ktDwwAvcV2qqSoA6H49ur",
    "sourcehandle": "yes",
    "target": "jm_Rhj2CVI_Yv4OZslAUW",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ktDwwAvcV2qqSoA6H49urno-fbe2yiJaAgQa033lXATO1input",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ktDwwAvcV2qqSoA6H49ur",
    "sourcehandle": "no",
    "target": "fbe2yiJaAgQa033lXATO1",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ktDwwAvcV2qqSoA6H49uryes-S2WR9WbUO2lKaGshG8_Ppinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ktDwwAvcV2qqSoA6H49ur",
    "sourcehandle": "yes",
    "target": "S2WR9WbUO2lKaGshG8_Pp",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ktDwwAvcV2qqSoA6H49urno-1m2YWLNGNSVz9aaYIfJIuinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ktDwwAvcV2qqSoA6H49ur",
    "sourcehandle": "no",
    "target": "1m2YWLNGNSVz9aaYIfJIu",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-jm_Rhj2CVI_Yv4OZslAUWno-DMCso1OEIqjB1lPLKUzHSinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "jm_Rhj2CVI_Yv4OZslAUW",
    "sourcehandle": "no",
    "target": "DMCso1OEIqjB1lPLKUzHS",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-S2WR9WbUO2lKaGshG8_Ppno-bx8ahgUuB7rOcLze37LbJinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "S2WR9WbUO2lKaGshG8_Pp",
    "sourcehandle": "no",
    "target": "bx8ahgUuB7rOcLze37LbJ",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-fbe2yiJaAgQa033lXATO1no-g7y_U3muCH_YWRTjPIl_Sinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "fbe2yiJaAgQa033lXATO1",
    "sourcehandle": "no",
    "target": "g7y_U3muCH_YWRTjPIl_S",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-1m2YWLNGNSVz9aaYIfJIuno-UNGeLpOF9CSt7pCaTo6uQinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "1m2YWLNGNSVz9aaYIfJIu",
    "sourcehandle": "no",
    "target": "UNGeLpOF9CSt7pCaTo6uQ",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-VhNcdxGhb5FNz6PkaF9SNyes-eBl97XtjA8KwduM0J8zo6input",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "VhNcdxGhb5FNz6PkaF9SN",
    "sourcehandle": "yes",
    "target": "eBl97XtjA8KwduM0J8zo6",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-eBl97XtjA8KwduM0J8zo6yes-ktDwwAvcV2qqSoA6H49urinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "eBl97XtjA8KwduM0J8zo6",
    "sourcehandle": "yes",
    "target": "ktDwwAvcV2qqSoA6H49ur",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-eBl97XtjA8KwduM0J8zo6no-3sScfFhiE-qfOMbSpZgR0input",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "eBl97XtjA8KwduM0J8zo6",
    "sourcehandle": "no",
    "target": "3sScfFhiE-qfOMbSpZgR0",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-jm_Rhj2CVI_Yv4OZslAUWyes-OFAAVVDKwYSCUTQQhs_Xjinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "jm_Rhj2CVI_Yv4OZslAUW",
    "sourcehandle": "yes",
    "target": "OFAAVVDKwYSCUTQQhs_Xj",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-S2WR9WbUO2lKaGshG8_Ppyes-aVYGk4nvN42GHJkSCWTKCinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "S2WR9WbUO2lKaGshG8_Pp",
    "sourcehandle": "yes",
    "target": "aVYGk4nvN42GHJkSCWTKC",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-fbe2yiJaAgQa033lXATO1yes-BTdeYK_AhNBR5DV8W0XPPinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "fbe2yiJaAgQa033lXATO1",
    "sourcehandle": "yes",
    "target": "BTdeYK_AhNBR5DV8W0XPP",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-1m2YWLNGNSVz9aaYIfJIuyes-nN6Btz--ZAOQR4mwDRyAHinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "1m2YWLNGNSVz9aaYIfJIu",
    "sourcehandle": "yes",
    "target": "nN6Btz--ZAOQR4mwDRyAH",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Payment Link",
  "name": "Payment Link",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":-334.1763458960038,\"y\":191.87608403093827,\"zoom\":0.8705772002909622}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"after_insert\",\n    \"doctype\": \"Program Enrollment\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "sWcnlymJyz9zfFwR6Wh5S",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": -90\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Student\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nvariables[\\\"recipient\\\"] = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nvariables[\\\"first_name\\\"] = doc.student_name\\npe = frappe.get_all(\\\"Program Enrollment\\\",{\\\"student\\\":doc.student, \\\"docstatus\\\":1})\\n\\nvariables[\\\"is_new\\\"] = len(pe) == 1\\n\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "584Vv8EY9zbmvQii7mUjm",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 60\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"expression\": \"return variables.get(\\\"is_new\\\")\",\n    \"filters\": [],\n    \"node_label\": \"Filter New and Old Student\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "ljFLq-WhJKM1mY2EyIneq",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Welcome email (original content)\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "ibJjFd348XmCAyrP7pqx-",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 330\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-sWcnlymJyz9zfFwR6Wh5Soutput-584Vv8EY9zbmvQii7mUjminput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "sWcnlymJyz9zfFwR6Wh5S",
    "sourcehandle": "output",
    "target": "584Vv8EY9zbmvQii7mUjm",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_template\": \"Welcome Email\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "b1PGxqRKsrmlF-u0qC3Aq",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1170,\n    \"y\": 270\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-584Vv8EY9zbmvQii7mUjmoutput-ljFLq-WhJKM1mY2EyIneqinput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "584Vv8EY9zbmvQii7mUjm",
    "sourcehandle": "output",
    "target": "ljFLq-WhJKM1mY2EyIneq",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ljFLq-WhJKM1mY2EyIneqyes-ibJjFd348XmCAyrP7pqx-input",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ljFLq-WhJKM1mY2EyIneq",
    "sourcehandle": "yes",
    "target": "ibJjFd348XmCAyrP7pqx-",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ljFLq-WhJKM1mY2EyIneqno-b1PGxqRKsrmlF-u0qC3Aqinput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ljFLq-WhJKM1mY2EyIneq",
    "sourcehandle": "no",
    "target": "b1PGxqRKsrmlF-u0qC3Aq",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Welcome Email",
  "name": "Welcome Email",
  "status": "updated",
  "variable_list": "[]",
  "viewport": "{\"x\":-278,\"y\":121,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"after_insert\",\n    \"doctype\": \"Rules and Regulation Submission\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "UruhSVrni8e7wn77Gsqnu",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"node_label\": \"Get Context\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nstudent_doc = frappe.get_doc(\\\"Student\\\", doc.student)\\npdf = frappe.db.get_value(\\n    \\\"Rules and Regulation Template\\\",\\n    doc.rules_and_regulation_template,\\n    \\\"pdf\\\",\\n)\\n\\nsite_url = frappe.utils.get_url()\\npdf_url = site_url + pdf\\n\\nfirst_name = student_doc.first_name\\nfather_name = frappe.db.get_value(\\n    \\\"Student Guardian\\\", {\\\"parent\\\": doc.student, \\\"relation\\\": \\\"Father\\\"}, \\\"guardian_name\\\"\\n)\\nmother_name = frappe.db.get_value(\\n    \\\"Student Guardian\\\", {\\\"parent\\\": doc.student, \\\"relation\\\": \\\"Mother\\\"}, \\\"guardian_name\\\"\\n)\\ncontext = {\\n    \\\"refno\\\": student_doc.reference_number,\\n    \\\"first_name\\\": first_name.capitalize() if first_name else \\\"\\\",\\n    \\\"mother_name\\\": mother_name.capitalize() if mother_name else \\\"\\\",\\n    \\\"father_name\\\": father_name.capitalize() if father_name else \\\"\\\",\\n    \\\"submitted_with_response\\\": doc.submitted_with_response,\\n    \\\"submitted_date\\\": doc.submitted_date,\\n    \\\"otp_entered\\\": doc.otp_entered,\\n    \\\"otp_sent_to_number\\\": doc.otp_sent_to_contact_no,\\n    \\\"otp_sent_to_email\\\": doc.otp_sent_to_email_id,\\n    \\\"ip_address\\\": doc.ip_address,\\n    \\\"user_info\\\": doc.user_info,\\n    \\\"link\\\": pdf_url,\\n}\\n\\nvariables[\\\"extra_email_args\\\"] = {}\\nvariables[\\\"extra_email_args\\\"][\\\"attachments\\\"] = [{\\\"doctype\\\": doc.doctype, \\\"name\\\":doc.name}]\\nvariables[\\\"recipient\\\"] = email\\nvariables[\\\"context\\\"] = context\\n\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "8SaqHGoRi7Q0iWuaripLL",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": 30\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_template\": \"Rules and Regulations\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true\n}",
    "element_type": "Action",
    "id": "Ih4wfjdvfw85nRjlhpvia",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": 180\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-UruhSVrni8e7wn77Gsqnuoutput-8SaqHGoRi7Q0iWuaripLLinput",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "UruhSVrni8e7wn77Gsqnu",
    "sourcehandle": "output",
    "target": "8SaqHGoRi7Q0iWuaripLL",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-8SaqHGoRi7Q0iWuaripLLoutput-Ih4wfjdvfw85nRjlhpviainput",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "8SaqHGoRi7Q0iWuaripLL",
    "sourcehandle": "output",
    "target": "Ih4wfjdvfw85nRjlhpvia",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Rules and Regulation Submission",
  "name": "Rules and Regulation Submission",
  "status": "updated",
  "variable_list": "[]",
  "viewport": "{\"x\":-300,\"y\":216,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Payment Request\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "Dee4oHV3XXZRXp0B5DqTG",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Fee Receipt"
   },
   {
    "data": "{\n    \"node_label\": \"Get Arguments\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"student_email_id\\\")\\n\\npayment_entries = frappe.get_all(\\n    \\\"Payment Entry\\\", {\\\"payment_request\\\": doc.name}\\n)\\n\\nprint_format = frappe.db.get_value(\\\"Fees Settings\\\", None, \\\"print_format\\\")\\n\\nletter_head = None\\nif doc.school:\\n    letter_head = frappe.db.get_value(\\\"School\\\", doc.school, 'letter_head')\\nelse:\\n    letter_head = frappe.db.get_value(\\\"Company\\\", doc.company, 'default_letter_head')\\n\\nattachments = [\\n    {\\n        \\\"doctype\\\": \\\"Payment Entry\\\",\\n        \\\"name\\\": pe.name,\\n        \\\"file_name\\\": pe.name,\\n        \\\"print_format\\\": print_format,\\n        \\\"print_letterhead\\\": True,\\n        \\\"letterhead\\\": letter_head,\\n    }\\n    for pe in payment_entries\\n]\\n\\nvariables[\\\"extra_email_args\\\"] = {}\\nvariables[\\\"extra_email_args\\\"][\\\"attachments\\\"] = attachments\\nvariables[\\\"recipient\\\"] = email\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "b0n3ZlAiRMoZvPIlb0uav",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": 30\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Please Find the attached fee receipt\",\n    \"email_subject\": \"Fee Receipt\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "mydH6M9zb4TA05WGnb9Wb",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-Dee4oHV3XXZRXp0B5DqTGoutput-b0n3ZlAiRMoZvPIlb0uavinput",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "Dee4oHV3XXZRXp0B5DqTG",
    "sourcehandle": "output",
    "target": "b0n3ZlAiRMoZvPIlb0uav",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-b0n3ZlAiRMoZvPIlb0uavoutput-mydH6M9zb4TA05WGnb9Wbinput",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "b0n3ZlAiRMoZvPIlb0uav",
    "sourcehandle": "output",
    "target": "mydH6M9zb4TA05WGnb9Wb",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Fee Receipt",
  "name": "Fee Receipt",
  "status": "updated",
  "variable_list": "[]",
  "viewport": "{\"x\":10,\"y\":200,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Student Applicant\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "i2Jauv8Vf8xyUrjwDXizw",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": -75\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Student Referral"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Students\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.custom_referred_by, \\\"student_email_id\\\")\\n\\nfirst_name = frappe.db.get_value(\\\"Student\\\", doc.custom_referred_by, \\\"first_name\\\")\\n\\nvariables[\\\"recipient\\\"] = email\\nvariables[\\\"first_name\\\"] = first_name\\nvariables[\\\"referred_name\\\"] = doc.first_name\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "y5lVVHqsSuB3wv8JaJqED",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": 90\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Dear {{first_name}},\\n      You have successfully referred {{referred_name}}. The referred discount will be applied to your fees soon.\\n\",\n    \"email_subject\": \"Dear {{first_name}},  You have successfully referred {{referred_name}}. \",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "2wFgz91PLkA7SPCQP40iL",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": 270\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-i2Jauv8Vf8xyUrjwDXizwoutput-y5lVVHqsSuB3wv8JaJqEDinput",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "i2Jauv8Vf8xyUrjwDXizw",
    "sourcehandle": "output",
    "target": "y5lVVHqsSuB3wv8JaJqED",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-y5lVVHqsSuB3wv8JaJqEDoutput-2wFgz91PLkA7SPCQP40iLinput",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "y5lVVHqsSuB3wv8JaJqED",
    "sourcehandle": "output",
    "target": "2wFgz91PLkA7SPCQP40iL",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Student Referral",
  "name": "Student Referral",
  "status": "updated",
  "variable_list": "[]",
  "viewport": "{\"x\":10,\"y\":200,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Fee Advance\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "9CpFQkSVJvXn4ut_91Jna",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1140,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Undertaking OTP"
   },
   {
    "data": "{\n    \"doctype\": \"Fees\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "FifTJtZNKt0Q7xP7XTPRi",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 615,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Undertaking OTP"
   },
   {
    "data": "{\n    \"node_label\": \"Generate OTP\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nvariables[\\\"recipient\\\"] = email\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "Qian3GkT4K0XlcvgZnLwN",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 60\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Here is the OTP For Undertaking Submission: {{otp}}\",\n    \"email_subject\": \"OTP For Undertaking Submission\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true\n}",
    "element_type": "Action",
    "id": "XgffkO_8YcUyxi-DP8Yu7",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 300\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"dotted_path\": \"edu_quality.public.py.undertaking.generate_otp\",\n    \"enqueue\": false,\n    \"payload\": \"\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "932Bg3N3q6jA6UAnlu1aN",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 180\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "frappe_exec_dotted_path"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-9CpFQkSVJvXn4ut_91Jnaoutput-Qian3GkT4K0XlcvgZnLwNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "9CpFQkSVJvXn4ut_91Jna",
    "sourcehandle": "output",
    "target": "Qian3GkT4K0XlcvgZnLwN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-FifTJtZNKt0Q7xP7XTPRioutput-Qian3GkT4K0XlcvgZnLwNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "FifTJtZNKt0Q7xP7XTPRi",
    "sourcehandle": "output",
    "target": "Qian3GkT4K0XlcvgZnLwN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-Qian3GkT4K0XlcvgZnLwNoutput-932Bg3N3q6jA6UAnlu1aNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "Qian3GkT4K0XlcvgZnLwN",
    "sourcehandle": "output",
    "target": "932Bg3N3q6jA6UAnlu1aN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-932Bg3N3q6jA6UAnlu1aNoutput-XgffkO_8YcUyxi-DP8Yu7input",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "932Bg3N3q6jA6UAnlu1aN",
    "sourcehandle": "output",
    "target": "XgffkO_8YcUyxi-DP8Yu7",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Undertaking OTP",
  "name": "Undertaking OTP",
  "status": "updated",
  "variable_list": "[]",
  "viewport": "{\"x\":-89,\"y\":290,\"zoom\":1}"
 }
]


def execute():
    for d in data:
        if not frappe.db.exists("Funnel", {"name": d.get("name")}):
            doc = frappe.get_doc(d)
            doc.insert()
        else:
            doc = frappe.get_doc("Funnel", {"name": d.get("name")})
            doc.reload()
            doc.update(d)
            doc.save()