import frappe

data = [
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"on_submit\",\n    \"doctype\": \"Payment Request\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "V7lvg8fLqqnTjtnqkrP2F",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": -45\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"action\": \"after_submit\",\n    \"doctype\": \"Payment Request\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "hSDgNxAlKtedcGUdBcTx6",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 510,\n    \"y\": -45\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"action\": \"on_update_after_submit\",\n    \"doctype\": \"Payment Request\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "mFBbfIjC_b_tFrDKMhLhe",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1215,\n    \"y\": -45\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment links For 1st Installment For All Students\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "3sScfFhiE-qfOMbSpZgR0",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1140,\n    \"y\": 510\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Student\",\n    \"python_code\": \"# do required updates\\n# update variable e.g.\\ndoc = variables.get(\\\"doc\\\")\\n\\nacad_year = frappe.db.get_value(doc.reference_doctype, doc.reference_name, \\\"academic_year\\\")\\n\\nfirst_name = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"first_name\\\")\\nmiddle_name = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"middle_name\\\")\\nlast_name = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"last_name\\\")\\nreference_number = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"reference_number\\\")\\n\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"student_email_id\\\")\\n\\npayment_plan = frappe.db.get_value(doc.reference_doctype, doc.reference_name, \\\"payment_plan\\\")\\n\\npayplan_doc = frappe.get_doc(\\\"Payment Plan\\\", payment_plan)\\ninst_count = len(payplan_doc.payment_schedule)\\n\\npe = frappe.get_all(\\\"Program Enrollment\\\",{\\\"student\\\":doc.party, \\\"docstatus\\\":1})\\n\\nvariables[\\\"is_new\\\"] = len(pe) == 1\\n\\nvariables[\\\"first_name\\\"] = first_name\\nvariables[\\\"middle_name\\\"] = middle_name\\nvariables[\\\"last_name\\\"] = last_name\\nvariables[\\\"acad_year\\\"] = acad_year\\nvariables[\\\"link\\\"] = doc.payment_url\\nvariables[\\\"refno\\\"] = reference_number\\nvariables[\\\"inst_count\\\"] = inst_count\\nvariables[\\\"recipient\\\"] = email\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "60MS7MC_fA4ZM-B_oL48R",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 60\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-V7lvg8fLqqnTjtnqkrP2Foutput-60MS7MC_fA4ZM-B_oL48Rinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "V7lvg8fLqqnTjtnqkrP2F",
    "sourcehandle": "output",
    "target": "60MS7MC_fA4ZM-B_oL48R",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"expression\": \"doc = variables.get('doc')\\nif doc.payment_term:\\n    return True\\nelse:\\n    return False\",\n    \"node_label\": \"Filter Deposit and Normal Payment Link\",\n    \"submit\": true,\n    \"use_python_expression\": true\n}",
    "element_type": "Action",
    "id": "VhNcdxGhb5FNz6PkaF9SN",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Deposit Link (Original Content)\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "V1FggHybsRoyMO2N4PJ0C",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1155,\n    \"y\": 240\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"expression\": \"doc = variables.get('doc')\\nif doc.payment_term == \\\"Term 1\\\":\\n    return True\\nelse:\\n    return False\",\n    \"node_label\": \"Filter Installment\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "fQE-aU5qgC_NUWLsMb5wT",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1140,\n    \"y\": 375\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_template\": \"Payment Link\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "742VMSnt8TVUmlk5TgEEm",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1440,\n    \"y\": 450\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-60MS7MC_fA4ZM-B_oL48Routput-VhNcdxGhb5FNz6PkaF9SNinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "60MS7MC_fA4ZM-B_oL48R",
    "sourcehandle": "output",
    "target": "VhNcdxGhb5FNz6PkaF9SN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"expression\": \"return variables.get(\\\"is_new\\\")\\n\",\n    \"filters\": [],\n    \"node_label\": \"Is New Student..??\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "GxwJTzFEli1Wf-GjjyOcs",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 330\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Payment link for New Students Std. 1 to 10\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "OFAAVVDKwYSCUTQQhs_Xj",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 810,\n    \"y\": 510\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-VhNcdxGhb5FNz6PkaF9SNno-V1FggHybsRoyMO2N4PJ0Cinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "VhNcdxGhb5FNz6PkaF9SN",
    "sourcehandle": "no",
    "target": "V1FggHybsRoyMO2N4PJ0C",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-fQE-aU5qgC_NUWLsMb5wTyes-3sScfFhiE-qfOMbSpZgR0input",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "fQE-aU5qgC_NUWLsMb5wT",
    "sourcehandle": "yes",
    "target": "3sScfFhiE-qfOMbSpZgR0",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-VhNcdxGhb5FNz6PkaF9SNyes-GxwJTzFEli1Wf-GjjyOcsinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "VhNcdxGhb5FNz6PkaF9SN",
    "sourcehandle": "yes",
    "target": "GxwJTzFEli1Wf-GjjyOcs",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-GxwJTzFEli1Wf-GjjyOcsno-fQE-aU5qgC_NUWLsMb5wTinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "GxwJTzFEli1Wf-GjjyOcs",
    "sourcehandle": "no",
    "target": "fQE-aU5qgC_NUWLsMb5wT",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-fQE-aU5qgC_NUWLsMb5wTno-742VMSnt8TVUmlk5TgEEminput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "fQE-aU5qgC_NUWLsMb5wT",
    "sourcehandle": "no",
    "target": "742VMSnt8TVUmlk5TgEEm",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-GxwJTzFEli1Wf-GjjyOcsyes-OFAAVVDKwYSCUTQQhs_Xjinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "GxwJTzFEli1Wf-GjjyOcs",
    "sourcehandle": "yes",
    "target": "OFAAVVDKwYSCUTQQhs_Xj",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-mFBbfIjC_b_tFrDKMhLheoutput-60MS7MC_fA4ZM-B_oL48Rinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "mFBbfIjC_b_tFrDKMhLhe",
    "sourcehandle": "output",
    "target": "60MS7MC_fA4ZM-B_oL48R",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-hSDgNxAlKtedcGUdBcTx6output-60MS7MC_fA4ZM-B_oL48Rinput",
    "parent": "Payment Link",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "hSDgNxAlKtedcGUdBcTx6",
    "sourcehandle": "output",
    "target": "60MS7MC_fA4ZM-B_oL48R",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Payment Link",
  "modified": "2024-01-08 17:40:03.295188",
  "name": "Payment Link",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":-457.7198029238791,\"y\":95.58805010220561,\"zoom\":1.1403558880516809}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"after_insert\",\n    \"doctype\": \"Program Enrollment\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "sWcnlymJyz9zfFwR6Wh5S",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": -90\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Student\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nvariables[\\\"recipient\\\"] = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nvariables[\\\"first_name\\\"] = doc.student_name\\npe = frappe.get_all(\\\"Program Enrollment\\\",{\\\"student\\\":doc.student, \\\"docstatus\\\":1})\\n\\nvariables[\\\"is_new\\\"] = len(pe) == 1\\n\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "584Vv8EY9zbmvQii7mUjm",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 60\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"expression\": \"return variables.get(\\\"is_new\\\")\",\n    \"filters\": [],\n    \"node_label\": \"Filter New and Old Student\",\n    \"submit\": true,\n    \"use_python_expression\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "ljFLq-WhJKM1mY2EyIneq",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "var_filter"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_subject\": \"\",\n    \"email_template\": \"Welcome email (original content)\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "ibJjFd348XmCAyrP7pqx-",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 840,\n    \"y\": 330\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-sWcnlymJyz9zfFwR6Wh5Soutput-584Vv8EY9zbmvQii7mUjminput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "sWcnlymJyz9zfFwR6Wh5S",
    "sourcehandle": "output",
    "target": "584Vv8EY9zbmvQii7mUjm",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_template\": \"Welcome Email\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "b1PGxqRKsrmlF-u0qC3Aq",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1170,\n    \"y\": 270\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-584Vv8EY9zbmvQii7mUjmoutput-ljFLq-WhJKM1mY2EyIneqinput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "584Vv8EY9zbmvQii7mUjm",
    "sourcehandle": "output",
    "target": "ljFLq-WhJKM1mY2EyIneq",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ljFLq-WhJKM1mY2EyIneqyes-ibJjFd348XmCAyrP7pqx-input",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ljFLq-WhJKM1mY2EyIneq",
    "sourcehandle": "yes",
    "target": "ibJjFd348XmCAyrP7pqx-",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-ljFLq-WhJKM1mY2EyIneqno-b1PGxqRKsrmlF-u0qC3Aqinput",
    "parent": "Welcome Email",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "ljFLq-WhJKM1mY2EyIneq",
    "sourcehandle": "no",
    "target": "b1PGxqRKsrmlF-u0qC3Aq",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Welcome Email",
  "modified": "2024-01-05 18:00:40.995589",
  "name": "Welcome Email",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":-278,\"y\":121,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"action\": \"after_insert\",\n    \"doctype\": \"Rules and Regulation Submission\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "UruhSVrni8e7wn77Gsqnu",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "document_event_trigger"
   },
   {
    "data": "{\n    \"node_label\": \"Get Context\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nstudent_doc = frappe.get_doc(\\\"Student\\\", doc.student)\\npdf = frappe.db.get_value(\\n    \\\"Rules and Regulation Template\\\",\\n    doc.rules_and_regulation_template,\\n    \\\"pdf\\\",\\n)\\n\\nsite_url = frappe.utils.get_url()\\npdf_url = site_url + pdf\\n\\nfirst_name = student_doc.first_name\\nfather_name = frappe.db.get_value(\\n    \\\"Student Guardian\\\", {\\\"parent\\\": doc.student, \\\"relation\\\": \\\"Father\\\"}, \\\"guardian_name\\\"\\n)\\nmother_name = frappe.db.get_value(\\n    \\\"Student Guardian\\\", {\\\"parent\\\": doc.student, \\\"relation\\\": \\\"Mother\\\"}, \\\"guardian_name\\\"\\n)\\ncontext = {\\n    \\\"refno\\\": student_doc.reference_number,\\n    \\\"first_name\\\": first_name.capitalize() if first_name else \\\"\\\",\\n    \\\"mother_name\\\": mother_name.capitalize() if mother_name else \\\"\\\",\\n    \\\"father_name\\\": father_name.capitalize() if father_name else \\\"\\\",\\n    \\\"submitted_with_response\\\": doc.submitted_with_response,\\n    \\\"submitted_date\\\": doc.submitted_date,\\n    \\\"otp_entered\\\": doc.otp_entered,\\n    \\\"otp_sent_to_number\\\": doc.otp_sent_to_contact_no,\\n    \\\"otp_sent_to_email\\\": doc.otp_sent_to_email_id,\\n    \\\"ip_address\\\": doc.ip_address,\\n    \\\"user_info\\\": doc.user_info,\\n    \\\"link\\\": pdf_url,\\n}\\n\\nvariables[\\\"extra_email_args\\\"] = {}\\nvariables[\\\"extra_email_args\\\"][\\\"attachments\\\"] = [{\\\"doctype\\\": doc.doctype, \\\"name\\\":doc.name}]\\nvariables[\\\"recipient\\\"] = email\\nvariables[\\\"context\\\"] = context\\n\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "8SaqHGoRi7Q0iWuaripLL",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": 30\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"\",\n    \"email_template\": \"Rules and Regulations\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": true,\n    \"send_to_assigned_users\": false,\n    \"submit\": true\n}",
    "element_type": "Action",
    "id": "Ih4wfjdvfw85nRjlhpvia",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 855,\n    \"y\": 180\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-UruhSVrni8e7wn77Gsqnuoutput-8SaqHGoRi7Q0iWuaripLLinput",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "UruhSVrni8e7wn77Gsqnu",
    "sourcehandle": "output",
    "target": "8SaqHGoRi7Q0iWuaripLL",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-8SaqHGoRi7Q0iWuaripLLoutput-Ih4wfjdvfw85nRjlhpviainput",
    "parent": "Rules and Regulation Submission",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "8SaqHGoRi7Q0iWuaripLL",
    "sourcehandle": "output",
    "target": "Ih4wfjdvfw85nRjlhpvia",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Rules and Regulation Submission",
  "modified": "2024-01-05 18:06:13.607363",
  "name": "Rules and Regulation Submission",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":-300,\"y\":216,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Payment Request\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "Dee4oHV3XXZRXp0B5DqTG",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Fee Receipt"
   },
   {
    "data": "{\n    \"node_label\": \"Get Arguments\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.party, \\\"student_email_id\\\")\\n\\npayment_entries = frappe.get_all(\\n    \\\"Payment Entry\\\", {\\\"payment_request\\\": doc.name}\\n)\\n\\nprint_format = frappe.db.get_value(\\\"Fees Settings\\\", None, \\\"print_format\\\")\\n\\nletter_head = None\\nif doc.school:\\n    letter_head = frappe.db.get_value(\\\"School\\\", doc.school, 'letter_head')\\nelse:\\n    letter_head = frappe.db.get_value(\\\"Company\\\", doc.company, 'default_letter_head')\\n\\nattachments = [\\n    {\\n        \\\"doctype\\\": \\\"Payment Entry\\\",\\n        \\\"name\\\": pe.name,\\n        \\\"file_name\\\": pe.name,\\n        \\\"print_format\\\": print_format,\\n        \\\"print_letterhead\\\": True,\\n        \\\"letterhead\\\": letter_head,\\n    }\\n    for pe in payment_entries\\n]\\n\\nvariables[\\\"extra_email_args\\\"] = {}\\nvariables[\\\"extra_email_args\\\"][\\\"attachments\\\"] = attachments\\nvariables[\\\"recipient\\\"] = email\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "b0n3ZlAiRMoZvPIlb0uav",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": 30\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Please Find the attached fee receipt\",\n    \"email_subject\": \"Fee Receipt\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "mydH6M9zb4TA05WGnb9Wb",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1050,\n    \"y\": 195\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-Dee4oHV3XXZRXp0B5DqTGoutput-b0n3ZlAiRMoZvPIlb0uavinput",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "Dee4oHV3XXZRXp0B5DqTG",
    "sourcehandle": "output",
    "target": "b0n3ZlAiRMoZvPIlb0uav",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-b0n3ZlAiRMoZvPIlb0uavoutput-mydH6M9zb4TA05WGnb9Wbinput",
    "parent": "Fee Receipt",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "b0n3ZlAiRMoZvPIlb0uav",
    "sourcehandle": "output",
    "target": "mydH6M9zb4TA05WGnb9Wb",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Fee Receipt",
  "modified": "2024-01-05 17:09:08.196342",
  "name": "Fee Receipt",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":10,\"y\":200,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Student Applicant\",\n    \"submit\": true\n}",
    "element_type": "Trigger",
    "id": "i2Jauv8Vf8xyUrjwDXizw",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": -75\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Student Referral"
   },
   {
    "data": "{\n    \"node_label\": \"Get Details of Students\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.custom_referred_by, \\\"student_email_id\\\")\\n\\nfirst_name = frappe.db.get_value(\\\"Student\\\", doc.custom_referred_by, \\\"first_name\\\")\\n\\nvariables[\\\"recipient\\\"] = email\\nvariables[\\\"first_name\\\"] = first_name\\nvariables[\\\"referred_name\\\"] = doc.first_name\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "y5lVVHqsSuB3wv8JaJqED",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": 90\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Dear {{first_name}},\\n      You have successfully referred {{referred_name}}. The referred discount will be applied to your fees soon.\\n\",\n    \"email_subject\": \"Dear {{first_name}},  You have successfully referred {{referred_name}}. \",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "2wFgz91PLkA7SPCQP40iL",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 960,\n    \"y\": 270\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-i2Jauv8Vf8xyUrjwDXizwoutput-y5lVVHqsSuB3wv8JaJqEDinput",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "i2Jauv8Vf8xyUrjwDXizw",
    "sourcehandle": "output",
    "target": "y5lVVHqsSuB3wv8JaJqED",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-y5lVVHqsSuB3wv8JaJqEDoutput-2wFgz91PLkA7SPCQP40iLinput",
    "parent": "Student Referral",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "y5lVVHqsSuB3wv8JaJqED",
    "sourcehandle": "output",
    "target": "2wFgz91PLkA7SPCQP40iL",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Student Referral",
  "modified": "2024-01-05 22:44:43.805274",
  "name": "Student Referral",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":10,\"y\":200,\"zoom\":1}"
 },
 {
  "archived": 0,
  "docstatus": 0,
  "doctype": "Funnel",
  "funnel_definition": [
   {
    "data": "{\n    \"doctype\": \"Fee Advance\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "9CpFQkSVJvXn4ut_91Jna",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 1140,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Undertaking OTP"
   },
   {
    "data": "{\n    \"doctype\": \"Fees\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Trigger",
    "id": "FifTJtZNKt0Q7xP7XTPRi",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 615,\n    \"y\": -105\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "Undertaking OTP"
   },
   {
    "data": "{\n    \"node_label\": \"Generate OTP\",\n    \"python_code\": \"doc = variables.get(\\\"doc\\\")\\n\\nemail = frappe.db.get_value(\\\"Student\\\", doc.student, \\\"student_email_id\\\")\\n\\nvariables[\\\"recipient\\\"] = email\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "Qian3GkT4K0XlcvgZnLwN",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 60\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "exec_python"
   },
   {
    "data": "{\n    \"email_account\": \"Notifications\",\n    \"email_content\": \"Here is the OTP For Undertaking Submission: {{otp}}\",\n    \"email_subject\": \"OTP For Undertaking Submission\",\n    \"recepients\": [\n        {\n            \"cc\": \"\",\n            \"recepientField\": \"\",\n            \"recipient\": \"{{recipient}}\"\n        }\n    ],\n    \"select_template\": false,\n    \"send_to_assigned_users\": false,\n    \"submit\": true\n}",
    "element_type": "Action",
    "id": "XgffkO_8YcUyxi-DP8Yu7",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 300\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "send_mail"
   },
   {
    "data": "{\n    \"dotted_path\": \"edu_quality.public.py.undertaking.generate_otp\",\n    \"enqueue\": false,\n    \"payload\": \"\",\n    \"submit\": true,\n    \"variable_path_for_output\": \"\"\n}",
    "element_type": "Action",
    "id": "932Bg3N3q6jA6UAnlu1aN",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": "{\n    \"x\": 870,\n    \"y\": 180\n}",
    "source": None,
    "sourcehandle": None,
    "target": None,
    "targethandle": None,
    "type": "frappe_exec_dotted_path"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-9CpFQkSVJvXn4ut_91Jnaoutput-Qian3GkT4K0XlcvgZnLwNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "9CpFQkSVJvXn4ut_91Jna",
    "sourcehandle": "output",
    "target": "Qian3GkT4K0XlcvgZnLwN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-FifTJtZNKt0Q7xP7XTPRioutput-Qian3GkT4K0XlcvgZnLwNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "FifTJtZNKt0Q7xP7XTPRi",
    "sourcehandle": "output",
    "target": "Qian3GkT4K0XlcvgZnLwN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-Qian3GkT4K0XlcvgZnLwNoutput-932Bg3N3q6jA6UAnlu1aNinput",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "Qian3GkT4K0XlcvgZnLwN",
    "sourcehandle": "output",
    "target": "932Bg3N3q6jA6UAnlu1aN",
    "targethandle": "input",
    "type": "smoothstep"
   },
   {
    "data": None,
    "element_type": "edge",
    "id": "reactflow__edge-932Bg3N3q6jA6UAnlu1aNoutput-XgffkO_8YcUyxi-DP8Yu7input",
    "parent": "Undertaking OTP",
    "parentfield": "funnel_definition",
    "parenttype": "Funnel",
    "position": None,
    "source": "932Bg3N3q6jA6UAnlu1aN",
    "sourcehandle": "output",
    "target": "XgffkO_8YcUyxi-DP8Yu7",
    "targethandle": "input",
    "type": "smoothstep"
   }
  ],
  "funnel_name": "Undertaking OTP",
  "modified": "2024-01-08 18:27:09.749967",
  "name": "Undertaking OTP",
  "status": "published",
  "variable_list": "[]",
  "viewport": "{\"x\":-89,\"y\":290,\"zoom\":1}"
 }
]


def execute():
    for d in data:
        if not frappe.db.exists("Funnel", {"name": d.get("name")}):
            doc = frappe.get_doc(d)
            doc.insert()
        else:
            doc = frappe.get_doc("Funnel", d.get("name"))
            doc.update(d)
            doc.save()

